apiVersion: v1
entries:
  secrets-store-sync-controller:
  - apiVersion: v2
    appVersion: v0.0.3
    created: "2026-02-26T17:20:52.260406581Z"
    description: A Helm chart to install the Secrets Store Sync Controller and its
      associated resources inside a Kubernetes cluster.
    digest: 00a2a2523ba03f33bd94260c819076c750b50c5988e9378531329d9f18e85e41
    kubeVersion: '>=1.27.0-0'
    name: secrets-store-sync-controller
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-sync-controller/charts/secrets-store-sync-controller-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: v0.0.2
    created: "2025-07-18T15:42:50.616250632Z"
    description: A Helm chart to install the Secrets Store Sync Controller and its
      associated resources inside a Kubernetes cluster.
    digest: 48a3e20fb1697d32b21f6a9e75dfe90b2db2f6a4d7b4a1d2855c9e427ce799e8
    kubeVersion: '>=1.27.0-0'
    name: secrets-store-sync-controller
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-sync-controller/charts/secrets-store-sync-controller-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: v0.0.1
    created: "2025-05-08T22:41:34.273910842Z"
    description: A Helm chart to install the Secrets Store Sync Controller and its
      associated resources inside a Kubernetes cluster.
    digest: 5494edd8efea6ca62ccb1380c937c74bc0832f22e4be6f134f88642682f1adae
    kubeVersion: '>=1.27.0'
    name: secrets-store-sync-controller
    urls:
    - https://kubernetes-sigs.github.io/secrets-store-sync-controller/charts/secrets-store-sync-controller-0.0.1.tgz
    version: 0.0.1
generated: "2026-02-26T17:20:52.259631289Z"
