apiVersion: v2
name: secrets-store-sync-controller
version: 0.0.2
appVersion: v0.0.2
kubeVersion: ">=1.30.0-0"
description: A Helm chart to install the Secrets Store Sync Controller and its associated resources inside a Kubernetes cluster.
