{{- if .Values.validatingAdmissionPolicies.applyPolicies -}}
{{ include "secrets-store-sync-controller.admissionApiVersion" . }}
kind: ValidatingAdmissionPolicy
metadata:
  name: "secrets-store-sync-controller-update-check-oldobject-policy"
spec:
  failurePolicy: Fail
  matchConditions:
    - name: 'user-is-secrets-store-sync-controller'
      expression: {{ include "chartname.matchConditionExpression" . | quote }}
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["UPDATE"]
      resources:   ["secrets"]
  variables:
  - name: hasOneSecretSyncOwner
    expression: "has(oldObject.metadata.ownerReferences) && (size(oldObject.metadata.ownerReferences) == 1 && oldObject.metadata.ownerReferences.all(o, o.kind == 'SecretSync' && o.apiVersion.startsWith('secret-sync.x-k8s.io/') && o.name == object.metadata.name))"
  - name: allowedSecretTypes
    expression: {{ include "chartname.secretTypesList" .Values.validatingAdmissionPolicies.allowedSecretTypes | quote }}
  validations:
  - expression: "variables.allowedSecretTypes == true && variables.hasOneSecretSyncOwner == true"
    message: "Only secrets with one secret sync owner and with types defined in the allowedSecretTypes list can be updated by the controller"
    messageExpression: "'secrets-store-sync-controller has failed to ' +  string(request.operation) + ' old secret with ' + string(object.type) + ' type ' + 'in the ' + string(request.namespace) + ' namespace. The controller can only update secrets in the allowed types list with a single secrets-store-sync-controller owner.'"
    reason: "Forbidden"
{{- end -}}
