name: E2E Provider Tests

on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'Registry for pulling images'
        required: true
        default: 'us-central1-docker.pkg.dev/k8s-staging-images/secrets-store-sync'
      imageName:
        description: 'Secret Store Sync Controller image name'
        required: true
        default: 'controller'
      imageVersion:
        description: 'image version for Secret Store Sync Controller'
        required: true
        default: 'vCHANGE_ME'

permissions:
  contents: read

jobs:
  e2e-test:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      matrix:
        KUBERNETES_VERSION: ["v1.28.13", "v1.29.8", "v1.30.4"]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup BATS
        uses: mig4/setup-bats@af9a00deb21b5d795cabfeaa8d9060410377686d # v1.2.0
        with:
          bats-version: 1.4.1
      - name: Setup helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
      - name: Setup Kubectl
        uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f # v4.0.0
      - name: Setup Kind
        uses: engineerd/setup-kind@71e45b960fc8dd50b4aeabf6eb6ef2ca0920b4c1 # v0.6.2
        with:
          version: "v0.23.0"
          image: "kindest/node:${{ matrix.KUBERNETES_VERSION }}"
          config: "hack/localsetup/kind-config.yaml"
      - name: Test
        run: |
          # GH action sets this var by default. We need to explicitly unset it so that build commit hash is not appended to image tag.
          unset CI

          make helm-manifest-install run-e2e-provider-tests
        env:
          REGISTRY: ${{ github.event.inputs.registry }}
          IMAGE_NAME: ${{ github.event.inputs.imageName }}
          IMAGE_VERSION: ${{ github.event.inputs.imageVersion }}
