name: 'Ensure codegen works'
on: [pull_request]

permissions:
  contents: read

jobs:
  verify-codegen:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.0.0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: "^1.25"
      - name: Run codegens
        run: |
          make generate
          make manifests
      - name: Verify git output
        shell: bash
        run: |
          if [ -n "$(git status -s)" ]; then
            echo 'Detected code generation changes'
            echo 'Make sure to run `make generate` and `make manifests` and commit those changes'
            git diff
            exit 1
          fi
