name: 'Ensure codegen works'
on: [pull_request]

permissions:
  contents: read

jobs:
  verify-codegen:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.0.0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: "^1.25"
      - name: Run codegens
        run: |
          make generate
          make manifests
      - name: Verify git output
        shell: bash
        run: |
          if [ -n "$(git status -s)" ]; then
            echo 'Detected code generation changes'
            echo 'Make sure to run `make generate` and `make manifests` and commit those changes'
            git diff
            exit 1
          fi
